CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS uploaded_files (
	id TEXT PRIMARY KEY,
	original_filename TEXT NOT NULL DEFAULT '',
	size BIGINT NOT NULL DEFAULT 0,
	mime_type TEXT NOT NULL DEFAULT '',
	detected_mime_type TEXT NOT NULL DEFAULT '',
	format TEXT NOT NULL,
	encoding TEXT NOT NULL DEFAULT '',
	sheet_name TEXT NOT NULL DEFAULT '',
	sheets JSONB NOT NULL DEFAULT '[]'::jsonb,
	header_row INTEGER NOT NULL DEFAULT 0,
	headers JSONB NOT NULL DEFAULT '[]'::jsonb,
	row_count INTEGER NOT NULL DEFAULT 0,
	column_count INTEGER NOT NULL DEFAULT 0,
	stats JSONB NOT NULL DEFAULT '{}'::jsonb,
	warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS size BIGINT NOT NULL DEFAULT 0;
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS mime_type TEXT NOT NULL DEFAULT '';
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS detected_mime_type TEXT NOT NULL DEFAULT '';
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS encoding TEXT NOT NULL DEFAULT '';
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS sheet_name TEXT NOT NULL DEFAULT '';
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS sheets JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS header_row INTEGER NOT NULL DEFAULT 0;
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS headers JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS stats JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE uploaded_files ADD COLUMN IF NOT EXISTS warnings JSONB NOT NULL DEFAULT '[]'::jsonb;

DO $migration$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = current_schema()
		  AND table_name = 'uploaded_files'
		  AND column_name = 'payload'
	) THEN
		ALTER TABLE uploaded_files ALTER COLUMN payload DROP NOT NULL;

		EXECUTE $sql$
			UPDATE uploaded_files
			SET size = COALESCE(NULLIF(payload->>'size', '')::bigint, size),
				mime_type = COALESCE(payload->>'mimeType', mime_type),
				detected_mime_type = COALESCE(payload->>'detectedMimeType', detected_mime_type),
				encoding = COALESCE(payload->>'encoding', encoding),
				sheet_name = COALESCE(payload->>'sheetName', sheet_name),
				sheets = COALESCE(payload->'sheets', sheets),
				header_row = COALESCE(NULLIF(payload->>'headerRow', '')::integer, header_row),
				headers = COALESCE(payload->'headers', headers),
				stats = COALESCE(payload->'stats', stats),
				warnings = COALESCE(payload->'warnings', warnings)
			WHERE payload IS NOT NULL
		$sql$;
	END IF;
END
$migration$;

ALTER TABLE uploaded_files DROP CONSTRAINT IF EXISTS chk_uploaded_files_format;
ALTER TABLE uploaded_files
	ADD CONSTRAINT chk_uploaded_files_format
	CHECK (format IN ('csv', 'xls', 'xlsx')) NOT VALID;

ALTER TABLE uploaded_files DROP CONSTRAINT IF EXISTS chk_uploaded_files_size;
ALTER TABLE uploaded_files
	ADD CONSTRAINT chk_uploaded_files_size CHECK (size >= 0) NOT VALID;

CREATE INDEX IF NOT EXISTS uploaded_files_created_at_idx
	ON uploaded_files (created_at DESC);
CREATE INDEX IF NOT EXISTS uploaded_files_format_idx
	ON uploaded_files (format);

CREATE TABLE IF NOT EXISTS file_rows (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	file_id TEXT NOT NULL REFERENCES uploaded_files(id) ON DELETE CASCADE,
	position INTEGER NOT NULL,
	row_number INTEGER NOT NULL,
	values JSONB NOT NULL,
	is_valid BOOLEAN NOT NULL DEFAULT TRUE,
	errors JSONB NOT NULL DEFAULT '[]'::jsonb,
	search_text TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT uq_file_rows_position UNIQUE (file_id, position),
	CONSTRAINT chk_file_rows_position CHECK (position > 0),
	CONSTRAINT chk_file_rows_row_number CHECK (row_number > 0),
	CONSTRAINT chk_file_rows_values CHECK (jsonb_typeof(values) = 'object'),
	CONSTRAINT chk_file_rows_errors CHECK (jsonb_typeof(errors) = 'array')
);

CREATE INDEX IF NOT EXISTS file_rows_file_id_row_number_idx
	ON file_rows (file_id, row_number);
CREATE INDEX IF NOT EXISTS file_rows_search_text_trgm_idx
	ON file_rows USING GIN (search_text gin_trgm_ops);

DO $migration$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = current_schema()
		  AND table_name = 'uploaded_files'
		  AND column_name = 'payload'
	) THEN
		EXECUTE $sql$
			INSERT INTO file_rows (
				file_id,
				position,
				row_number,
				values,
				is_valid,
				errors,
				search_text
			)
			SELECT
				uf.id,
				row_data.position::integer,
				GREATEST(1, COALESCE(NULLIF(uf.payload->>'headerRow', '')::integer, 1) + row_data.position::integer),
				row_data.row_values,
				invalid.errors IS NULL,
				COALESCE(invalid.errors, '[]'::jsonb),
				COALESCE((
					SELECT string_agg(field.value, ' ' ORDER BY field.key)
					FROM jsonb_each_text(row_data.row_values) AS field
				), '')
			FROM uploaded_files AS uf
			CROSS JOIN LATERAL jsonb_array_elements(COALESCE(uf.payload->'rows', '[]'::jsonb))
				WITH ORDINALITY AS row_data(row_values, position)
			LEFT JOIN LATERAL (
				SELECT invalid_row->'errors' AS errors
				FROM jsonb_array_elements(COALESCE(uf.payload->'invalidRows', '[]'::jsonb)) AS invalid_row
				WHERE NULLIF(invalid_row->>'row', '')::integer =
					COALESCE(NULLIF(uf.payload->>'headerRow', '')::integer, 1) + row_data.position::integer
				LIMIT 1
			) AS invalid ON TRUE
			WHERE uf.payload IS NOT NULL
			ON CONFLICT (file_id, position) DO NOTHING
		$sql$;
	END IF;
END
$migration$;

CREATE TABLE IF NOT EXISTS contacts (
	id TEXT PRIMARY KEY,
	phone TEXT NOT NULL,
	email TEXT NOT NULL DEFAULT '',
	name TEXT NOT NULL DEFAULT '',
	discount TEXT NOT NULL DEFAULT '',
	data JSONB NOT NULL DEFAULT '{}'::jsonb,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT uq_contacts_phone UNIQUE (phone)
);

DO $migration$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = current_schema()
		  AND table_name = 'contacts'
		  AND column_name = 'file_id'
	) THEN
		ALTER TABLE contacts DROP CONSTRAINT IF EXISTS contacts_file_id_fkey;
		ALTER TABLE contacts ALTER COLUMN file_id DROP NOT NULL;
	END IF;
END
$migration$;

ALTER TABLE contacts DROP CONSTRAINT IF EXISTS contacts_phone_key;
ALTER TABLE contacts DROP CONSTRAINT IF EXISTS uq_contacts_phone;
ALTER TABLE contacts ADD CONSTRAINT uq_contacts_phone UNIQUE (phone);

ALTER TABLE contacts DROP CONSTRAINT IF EXISTS chk_contacts_phone;
ALTER TABLE contacts
	ADD CONSTRAINT chk_contacts_phone
	CHECK (phone ~ '^\+7 \([0-9]{3}\) [0-9]{3}-[0-9]{2}-[0-9]{2}$') NOT VALID;

ALTER TABLE contacts DROP CONSTRAINT IF EXISTS chk_contacts_discount;
ALTER TABLE contacts
	ADD CONSTRAINT chk_contacts_discount
	CHECK (
		discount = '' OR
		(discount ~ '^[0-9]+([.][0-9]+)?$' AND discount::numeric BETWEEN 0 AND 100)
	) NOT VALID;

ALTER TABLE contacts DROP CONSTRAINT IF EXISTS chk_contacts_data;
ALTER TABLE contacts
	ADD CONSTRAINT chk_contacts_data CHECK (jsonb_typeof(data) = 'object') NOT VALID;

CREATE INDEX IF NOT EXISTS contacts_email_idx ON contacts (lower(email));

CREATE TABLE IF NOT EXISTS contact_sources (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	contact_id TEXT NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
	file_id TEXT REFERENCES uploaded_files(id) ON DELETE SET NULL,
	row_number INTEGER NOT NULL DEFAULT 0,
	action TEXT NOT NULL,
	incoming JSONB NOT NULL DEFAULT '{}'::jsonb,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT chk_contact_sources_row_number CHECK (row_number >= 0),
	CONSTRAINT chk_contact_sources_action CHECK (
		action IN ('created', 'matched', 'skipped', 'replaced', 'merged', 'fixed')
	),
	CONSTRAINT chk_contact_sources_incoming CHECK (jsonb_typeof(incoming) = 'object'),
	CONSTRAINT uq_contact_sources_event UNIQUE (contact_id, file_id, row_number, action)
);

CREATE INDEX IF NOT EXISTS contact_sources_file_id_idx
	ON contact_sources (file_id, row_number);
CREATE INDEX IF NOT EXISTS contact_sources_contact_id_idx
	ON contact_sources (contact_id, created_at DESC);

DO $migration$
BEGIN
	IF EXISTS (
		SELECT 1
		FROM information_schema.columns
		WHERE table_schema = current_schema()
		  AND table_name = 'contacts'
		  AND column_name = 'file_id'
	) THEN
		EXECUTE $sql$
			INSERT INTO contact_sources (contact_id, file_id, row_number, action, incoming)
			SELECT
				id,
				file_id,
				0,
				'created',
				jsonb_build_object(
					'phone', phone,
					'email', email,
					'name', name,
					'discount', discount,
					'data', data
				)
			FROM contacts
			WHERE file_id IS NOT NULL
			ON CONFLICT (contact_id, file_id, row_number, action) DO NOTHING
		$sql$;
	END IF;
END
$migration$;

CREATE TABLE IF NOT EXISTS contact_versions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	contact_id TEXT NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
	phone TEXT NOT NULL DEFAULT '',
	email TEXT NOT NULL DEFAULT '',
	name TEXT NOT NULL DEFAULT '',
	discount TEXT NOT NULL DEFAULT '',
	data JSONB NOT NULL DEFAULT '{}'::jsonb,
	file_id TEXT REFERENCES uploaded_files(id) ON DELETE SET NULL,
	action TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE contact_versions ALTER COLUMN file_id DROP NOT NULL;
ALTER TABLE contact_versions DROP CONSTRAINT IF EXISTS contact_versions_contact_id_fkey;
ALTER TABLE contact_versions
	ADD CONSTRAINT contact_versions_contact_id_fkey
	FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE RESTRICT;

ALTER TABLE contact_versions DROP CONSTRAINT IF EXISTS contact_versions_file_id_fkey;
ALTER TABLE contact_versions
	ADD CONSTRAINT contact_versions_file_id_fkey
	FOREIGN KEY (file_id) REFERENCES uploaded_files(id) ON DELETE SET NULL NOT VALID;

ALTER TABLE contact_versions DROP CONSTRAINT IF EXISTS chk_contact_versions_action;
ALTER TABLE contact_versions
	ADD CONSTRAINT chk_contact_versions_action
	CHECK (action IN ('created', 'updated', 'replaced', 'merged', 'fixed')) NOT VALID;

CREATE INDEX IF NOT EXISTS contact_versions_contact_id_idx
	ON contact_versions (contact_id, created_at DESC);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
	NEW.updated_at = now();
	RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS uploaded_files_set_updated_at ON uploaded_files;
CREATE TRIGGER uploaded_files_set_updated_at
	BEFORE UPDATE ON uploaded_files
	FOR EACH ROW
	EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS contacts_set_updated_at ON contacts;
CREATE TRIGGER contacts_set_updated_at
	BEFORE UPDATE ON contacts
	FOR EACH ROW
	EXECUTE FUNCTION set_updated_at();
