// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": [[ marshal .Schemes ]],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "[[escape .Description]]",
        "title": "[[.Title]]",
        "contact": {},
        "version": "[[.Version]]"
    },
    "host": "[[.Host]]",
    "basePath": "[[.BasePath]]",
    "paths": {
        "/api/contacts/resolve": {
            "post": {
                "description": "Применяет действие skip, replace или merge к несовпадающим данным одного телефона из выбранного файла.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contacts"
                ],
                "summary": "Разрешить один конфликт контакта",
                "parameters": [
                    {
                        "description": "Решение конфликта",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResolveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResolveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/contacts/resolve-all": {
            "post": {
                "description": "Применяет одно действие skip, replace или merge ко всем несовпадающим контактам выбранного файла.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contacts"
                ],
                "summary": "Разрешить все конфликты файла",
                "parameters": [
                    {
                        "description": "Общее решение конфликтов",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BatchResolveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResolveAllResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/contacts/save": {
            "post": {
                "description": "Переносит валидные строки загруженного файла в общий справочник контактов. Несовпадающие данные для существующего телефона возвращаются как конфликты.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contacts"
                ],
                "summary": "Сохранить контакты из файла",
                "parameters": [
                    {
                        "description": "Идентификатор загруженного файла",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SaveContactsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SaveContactsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/export": {
            "post": {
                "description": "Формирует сообщения по всем актуальным контактам PostgreSQL и возвращает UTF-8 CSV с колонками «Телефон» и «Сообщение».",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/csv",
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Экспортировать общую рассылку",
                "parameters": [
                    {
                        "description": "Шаблон сообщения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PreviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "notifications.csv",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Проверяет доступность PostgreSQL с таймаутом две секунды.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Проверить состояние приложения",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/preview": {
            "post": {
                "description": "Формирует сообщение для каждого актуального контакта PostgreSQL. Поддерживаются плейсхолдеры {{Телефон}}, {{Имя}}, {{Email}} и {{Скидка}}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Предпросмотр общей рассылки",
                "parameters": [
                    {
                        "description": "Шаблон сообщения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.PreviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.PreviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/rows/fix": {
            "post": {
                "description": "Повторно нормализует отредактированные пользователем строки файла и сохраняет корректные контакты в PostgreSQL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Проверить и сохранить исправленные строки",
                "parameters": [
                    {
                        "description": "Исправленные строки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.FixRowsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.FixRowResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/search": {
            "post": {
                "description": "Ищет подстроку без учёта регистра во всех ячейках ранее загруженного файла. Возвращает полные строки и колонки совпадений для подсветки.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Найти строки в файле",
                "parameters": [
                    {
                        "description": "Параметры поиска",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/upload": {
            "post": {
                "description": "Принимает CSV, XLS или XLSX, определяет структуру, нормализует данные и сохраняет все строки в PostgreSQL.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Files"
                ],
                "summary": "Загрузить и проверить файл",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV/XLS/XLSX-файл с клиентскими данными",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Имя листа XLS/XLSX; если не задано, используется первый лист",
                        "name": "sheet",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Некорректный запрос"
                }
            }
        },
        "handlers.FixRowsRequest": {
            "type": "object",
            "required": [
                "fileId",
                "rows"
            ],
            "properties": {
                "fileId": {
                    "type": "string",
                    "example": "2f656bc0-6227-49d3-9d09-b2d59bd21c52"
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.FixRowInput"
                    }
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "storage unavailable"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "degraded"
                    ],
                    "example": "ok"
                },
                "storage": {
                    "type": "string",
                    "enum": [
                        "postgres"
                    ],
                    "example": "postgres"
                }
            }
        },
        "handlers.NotificationItem": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "row": {
                    "type": "integer",
                    "example": 1
                },
                "text": {
                    "type": "string",
                    "example": "Здравствуйте, Анна! Ваша скидка: 10%."
                }
            }
        },
        "handlers.PreviewRequest": {
            "type": "object",
            "required": [
                "template"
            ],
            "properties": {
                "template": {
                    "type": "string",
                    "example": "Здравствуйте, {{Имя}}! Ваша скидка: {{Скидка}}."
                }
            }
        },
        "handlers.PreviewResponse": {
            "type": "object",
            "properties": {
                "notifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.NotificationItem"
                    }
                },
                "skipped": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "handlers.ResolveAllResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "enum": [
                        "skip",
                        "replace",
                        "merge"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ConflictAction"
                        }
                    ],
                    "example": "merge"
                },
                "resolved": {
                    "type": "integer",
                    "example": 3
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok"
                    ],
                    "example": "ok"
                }
            }
        },
        "handlers.ResolveResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "enum": [
                        "skip",
                        "replace",
                        "merge"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ConflictAction"
                        }
                    ],
                    "example": "merge"
                },
                "phone": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok"
                    ],
                    "example": "ok"
                }
            }
        },
        "handlers.SaveContactsRequest": {
            "type": "object",
            "required": [
                "fileId"
            ],
            "properties": {
                "fileId": {
                    "type": "string",
                    "example": "2f656bc0-6227-49d3-9d09-b2d59bd21c52"
                }
            }
        },
        "handlers.SaveContactsResponse": {
            "type": "object",
            "properties": {
                "conflicts": {
                    "description": "конфликты",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConflictInfo"
                    }
                },
                "saved": {
                    "description": "Сколько сохранено",
                    "type": "integer"
                },
                "skipped": {
                    "description": "Сколько пропущено",
                    "type": "integer"
                }
            }
        },
        "handlers.SearchMatch": {
            "type": "object",
            "properties": {
                "column": {
                    "type": "string",
                    "example": "Телефон"
                },
                "value": {
                    "type": "string",
                    "example": "+79991234567"
                }
            }
        },
        "handlers.SearchRequest": {
            "type": "object",
            "required": [
                "fileId",
                "query"
            ],
            "properties": {
                "fileId": {
                    "type": "string",
                    "example": "2f656bc0-6227-49d3-9d09-b2d59bd21c52"
                },
                "limit": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 100
                },
                "query": {
                    "type": "string",
                    "example": "+79"
                }
            }
        },
        "handlers.SearchResponse": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 100
                },
                "query": {
                    "type": "string",
                    "example": "+79"
                },
                "returned": {
                    "description": "Сколько вернули строк",
                    "type": "integer",
                    "example": 17
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SearchRow"
                    }
                },
                "totalMatches": {
                    "description": "Сколько всего совпадений",
                    "type": "integer",
                    "example": 17
                },
                "truncated": {
                    "description": "Обрезали ли количество",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "handlers.SearchRow": {
            "type": "object",
            "properties": {
                "matches": {
                    "description": "Массив совпадений (какие колонки совпали у данной строки)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SearchMatch"
                    }
                },
                "row": {
                    "type": "integer"
                },
                "values": {
                    "description": "Все строка целиком",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.UploadResponse": {
            "type": "object",
            "properties": {
                "detectedMimeType": {
                    "type": "string",
                    "example": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                },
                "detectedPhoneColumn": {
                    "type": "string",
                    "example": "Телефон"
                },
                "encoding": {
                    "type": "string",
                    "example": "UTF-8"
                },
                "fileId": {
                    "type": "string",
                    "example": "2f656bc0-6227-49d3-9d09-b2d59bd21c52"
                },
                "format": {
                    "type": "string",
                    "enum": [
                        "csv",
                        "xls",
                        "xlsx"
                    ],
                    "example": "xlsx"
                },
                "headerRow": {
                    "type": "integer",
                    "example": 1
                },
                "headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "invalidRows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.InvalidRow"
                    }
                },
                "mimeType": {
                    "type": "string",
                    "example": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                },
                "originalFilename": {
                    "type": "string",
                    "example": "clients.xlsx"
                },
                "previewRows": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "string"
                        }
                    }
                },
                "sheetName": {
                    "type": "string",
                    "example": "Клиенты"
                },
                "sheets": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "size": {
                    "type": "integer",
                    "example": 18432
                },
                "stats": {
                    "$ref": "#/definitions/models.ProcessingStats"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessingWarning"
                    }
                }
            }
        },
        "models.BatchResolveRequest": {
            "type": "object",
            "required": [
                "action",
                "fileId"
            ],
            "properties": {
                "action": {
                    "enum": [
                        "skip",
                        "replace",
                        "merge"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ConflictAction"
                        }
                    ],
                    "example": "merge"
                },
                "fileId": {
                    "type": "string",
                    "example": "2f656bc0-6227-49d3-9d09-b2d59bd21c52"
                }
            }
        },
        "models.ConflictAction": {
            "type": "string",
            "enum": [
                "skip",
                "replace",
                "merge"
            ],
            "x-enum-varnames": [
                "ConflictActionSkip",
                "ConflictActionReplace",
                "ConflictActionMerge"
            ]
        },
        "models.ConflictInfo": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConflictAction"
                    }
                },
                "differences": {
                    "description": "Отличные поля",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "existing": {
                    "description": "То, что уже лежит в базе",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "incoming": {
                    "description": "То, что прислал фронт",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "phone": {
                    "type": "string",
                    "example": "+79991234567"
                },
                "row": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "models.InvalidRow": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessingWarning"
                    }
                },
                "row": {
                    "type": "integer",
                    "example": 4
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ProcessingStats": {
            "type": "object",
            "properties": {
                "columnCount": {
                    "type": "integer",
                    "example": 4
                },
                "emptyRowCount": {
                    "type": "integer",
                    "example": 1
                },
                "invalidRowCount": {
                    "type": "integer",
                    "example": 3
                },
                "rowCount": {
                    "type": "integer",
                    "example": 100
                },
                "skippedRowCount": {
                    "type": "integer",
                    "example": 1
                },
                "validRowCount": {
                    "type": "integer",
                    "example": 96
                },
                "warningCount": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "models.ProcessingWarning": {
            "type": "object",
            "properties": {
                "column": {
                    "type": "string",
                    "example": "Email"
                },
                "message": {
                    "type": "string",
                    "example": "Некорректный email."
                },
                "row": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "models.ResolveRequest": {
            "type": "object",
            "required": [
                "action",
                "fileId",
                "phone"
            ],
            "properties": {
                "action": {
                    "enum": [
                        "skip",
                        "replace",
                        "merge"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ConflictAction"
                        }
                    ],
                    "example": "merge"
                },
                "fileId": {
                    "type": "string",
                    "example": "2f656bc0-6227-49d3-9d09-b2d59bd21c52"
                },
                "phone": {
                    "type": "string",
                    "example": "+79991234567"
                }
            }
        },
        "services.FixRowError": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessingWarning"
                    }
                },
                "rowNumber": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "services.FixRowInput": {
            "type": "object",
            "required": [
                "rowNumber",
                "values"
            ],
            "properties": {
                "rowNumber": {
                    "type": "integer",
                    "example": 4
                },
                "values": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "services.FixRowResult": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.FixRowError"
                    }
                },
                "fixed": {
                    "type": "integer",
                    "example": 2
                },
                "stats": {
                    "$ref": "#/definitions/models.ProcessingStats"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessingWarning"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "Состояние приложения и подключение к PostgreSQL",
            "name": "Health"
        },
        {
            "description": "Загрузка, разбор и исправление строк файлов",
            "name": "Files"
        },
        {
            "description": "Поиск по строкам ранее загруженного файла",
            "name": "Search"
        },
        {
            "description": "Сохранение контактов и разрешение конфликтов по телефону",
            "name": "Contacts"
        },
        {
            "description": "Предпросмотр и экспорт рассылки по всем контактам PostgreSQL",
            "name": "Notifications"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Task1 Client Data API",
	Description:      "API для загрузки клиентских CSV/XLS/XLSX, проверки и поиска строк, ведения контактов и подготовки рассылок.\nВсе операции с файлами и контактами используют PostgreSQL как единственное хранилище.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "[[",
	RightDelim:       "]]",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
